# Use Alpine as base image
FROM alpine:3.18

# Install Apache and Kerberos authentication module
RUN apk update && \
    apk add apache2 apache-mod-auth-kerb

# Copy the Apache configuration file and Kerberos configuration if needed
COPY config/apache.conf /etc/apache2/sites-available/000-default.conf
COPY --chown=www-data:www-data config/http.keytab /etc/apache2/http.keytab
COPY config/krb5.conf /etc/krb5.conf

# Set the default entrypoint
CMD ["httpd", "-D", "FOREGROUND"]