version: '3'

services:
  # Kerberos Server (KDC)
  kerberos-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: kerberos.example.com

  # Apache Server (with Kerberos authentication)
  apache-server:
    build:
      context: .
      dockerfile: Dockerfile.apache
    hostname: http.example.com
    depends_on:
      - kerberos-server
