name: Build and test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  checks:
    uses: grafana/k6-ci/.github/workflows/all.yml@precompiled-gotip