name: Build and test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    uses: grafana/k6-ci/.github/workflows/all.yml@ed9ce7ed320a35f30705f8e5fd3acba85cb5372e # main
